title: My Personal Site
description: Personal notes on code, math and research

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - code/index.md
  - math/index.md
  - research/index.md
  - thoughts/index.md
  - about.md
